export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_PROFILE = "SET_PROFILE";

export const SET_NOTIFICATIONS = "SET_NOTIFICATION";
export const SET_NOTIFICATION_AS_READ = "SET_NOTIFICATION_AS_READ";
export const MARK_ALL_AS_READ = "MARK_ALL_AS_READ";
