# Generated by Django 3.2.3 on 2021-05-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_follower_being_followed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='being_followed',
            new_name='following',
        ),
    ]
